In [ ]:
1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [4]:
#1. Write a Python Program to Add Two Matrices?

import numpy as np

a = np.array([[1,2] , [3,4]])
b = np.array([[2,3], [4,5]])
a+b

array([[3, 5],
       [7, 9]])

In [5]:
#2. Write a Python Program to Multiply Two Matrices?

a @ b

array([[10, 13],
       [22, 29]])

In [7]:
#3. Write a Python Program to Transpose a Matrix?

c = np.array([2,3,1,2,3,2]).reshape(1,-1)
c.T


array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [10]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

gven_str = input("Enter some random string = ")

wrd_lst = gven_str.split()

wrd_lst.sort()

print("The all sorted words of given sentence in Alphabetic order :")
for wrd in wrd_lst:
    print(wrd)


Enter some random string = hello good afternoon all
The all sorted words of given sentence in Alphabetic order :
afternoon
all
good
hello


In [11]:
#5. Write a Python Program to Remove Punctuation From a String?

import re

a_string = '!hi. wh?at is the weat[h]er lik?e.'
new_string = re.sub(r'[^\w\s]', '', a_string)

print(new_string)



hi what is the weather like
