Q1. What are the benefits of the built-in array package, if any?

The following are some advantages of arrays:

Arrays are similar to lists. The main difference is that arrays can store only one type of elements; whereas, lists can store different types of elements. When dealing with a huge number of elements, arrays use less memory than lists and they offer faster execution than lists.

The size of the array is not fixed in Python. Hence, we need not specify how many elements we are going to store into an array in the beginning.

Arrays can grow or shrink in memory dynamically (during runtime).

Arrays are useful to handle a collection of elements like a group of numbers or characters.

Methods that are useful to process the elements of any array are available in 'array' module.

Q2. What are some of the array package's limitations?

The traditional array module does not support multi-dimensional arrays.
An array which is formed will be homogeneous. That is, in an integer array only integer values can be stored, while in a float array only floating value and character array can have only characters.

Q3. Describe the main differences between the array and numpy packages.

The array package doesn't provide any help with numerical calculation with the items insdie it in number form 
while NumPy give you a wide variety of numerical operations. An array is a single dimensional entity which hold
the numerical data, while numpy can have more than 1 dimension.In case of array, item can be accessed by its
index position and it is easy task while in numpy item is accessed by its column and row index, which makes 
it slightly time taking. Same goes with appending operation.In case of array we do not form a tabular 
structure, while in numpy it forms a tabular structure.

In [3]:
#Q4. Explain the distinctions between the empty, ones, and zeros functions.

#The empty() function of NumPy creates an uninitialized array having shape and dtype as given to the empty() function.

import numpy as np
np.empty((2,4,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.29061074e-306],
        [8.34441742e-308, 1.78022342e-306],
        [6.23058028e-307, 9.79107872e-307]],

       [[6.89807188e-307, 7.56594375e-307],
        [6.23060065e-307, 1.78021527e-306],
        [8.34454050e-308, 1.11261027e-306],
        [1.15706896e-306, 1.33512173e-306]]])

In [5]:
#The zeros() function of NumPy creates a ndarray initialized with 0 values having shape and dtype as given as input.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
#The ones() function of NumPy creates a ndarray initialized with 1 having shape and dtype as given as input.
np.zeros(2)

array([0., 0.])

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

function : [callable] The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis.

In [9]:
#Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

b = np.array([2,3,1,2,3,2])
print(b+2)

[4 5 3 4 5 4]


In [13]:
#Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

b = np.array([2,3,1,2,3,2])
print(b += 2)

SyntaxError: invalid syntax (<ipython-input-13-bc5e68cfa77c>, line 4)

In [ ]:
Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

Yes it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array 
containing string values is the maximum length of any string present in the array.
Once set, it will only be able to store new string having length not more than the maximum length at the time 
of the creation. If we try to reassign some another string value having length greater than the maximum length
of the existing elements, it simply discards all the values beyond the maximum length accept upto those values 
which are under the limit.



In [ ]:
Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

It will simply add or multiply element to element at same position.The only requirement which must be met are:
1)Data type should be same.
2) Shape of the two matrices must be same


In [4]:
#Q10. What is the best way to use a Boolean array to mask another array?
import numpy as np
y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print(m.ndim)

[True, True, masked, masked]
1


In [ ]:
#Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

#Standard deviation can be calculated in many ways. If wee see the formula of SD, it says 
#std= Square Root of [ Summation of [square of (x-mean)/number of observation] ] .So this can be achive by:
    
1)Using math module :
import math
N = 1
avg=a
total=N
x=[1,2]
SD=math.sqrt((1-a)**2+(2-a)**2/N)

In [ ]:
#2)Using Numpy Array package
import numpy as np
SD=np.std(x)

In [ ]:
#3) General calculation without using any package
SD= (((1-avg)**2 + (2-avg)**2)/N)**1/2

12. What is the dimensionality of a Boolean mask-generated array?
A boolean array. Its shape will be used as window_size, and its entries are used to mask every window, resulting in dimensionality a.ndim + 1 as the final result, just as in the case of flatten is True.
